import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'en';

  String get currentLanguage => _currentLanguage;

  static const Map<String, String> languages = {
    'en': 'English',
    'hi': 'हिन्दी (Hindi)',
    'kn': 'ಕನ್ನಡ (Kannada)',
    'te': 'తెలుగు (Telugu)',
    'ta': 'தமிழ் (Tamil)',
    'ml': 'മലയാളം (Malayalam)',
  };

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language_pref') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    if (languages.containsKey(langCode)) {
      _currentLanguage = langCode;
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('language_pref', langCode);
      notifyListeners();
    }
  }

  String translate(String key) {
    return _dictionary[_currentLanguage]?[key] ?? _dictionary['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _dictionary = {
    'en': {
      'app_name': 'AgriLink',
      'tagline': 'Connecting Farmers to Customers',
      'welcome_back': 'Welcome Back',
      'login_continue': 'Login to continue',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'login': 'Login',
      'dont_have_account': "Don't have an account?",
      'register': 'Register',
      'register_title': 'Create Account',
      'register_subtitle': 'Sign up to get started',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'already_have_account': 'Already have an account?',
      'search_products': 'Search Products...',
      'categories': 'Categories',
      'featured_products': 'Featured Products',
      'farm_fresh_today': 'Farm Fresh Today',
      'farmer_spotlight': 'Farmer Spotlight',
      'add_to_cart': 'Add to Cart',
      'cart': 'Cart',
      'profile': 'Profile',
      'logout': 'Logout',
      'language_selection': 'Select Language',
      'voice_search': 'Speak to search',
      'otp_verification': 'OTP Verification',
      'enter_otp': 'Enter the 6-digit OTP sent to your phone',
      'verify': 'Verify',
      'resend_otp': 'Resend OTP',
      'checkout': 'Checkout',
      'subtotal': 'Subtotal',
      'delivery_charge': 'Delivery Charge',
      'gst': 'GST (5%)',
      'total': 'Total',
      'pay_now': 'Pay Now',
      'payment_success': 'Payment Successful!',
      'download_invoice': 'Download Invoice',
      'home': 'Home',
      'my_orders': 'My Orders',
    },
    'hi': {
      'app_name': 'एग्रीलिंक',
      'tagline': 'किसानों को ग्राहकों से जोड़ना',
      'welcome_back': 'आपका स्वागत है',
      'login_continue': 'आगे बढ़ने के लिए लॉगिन करें',
      'email': 'ईमेल',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए?',
      'login': 'लॉगिन करें',
      'dont_have_account': 'खाता नहीं है?',
      'register': 'पंजीकरण करें',
      'register_title': 'खाता बनाएं',
      'register_subtitle': 'शुरू करने के लिए साइन अप करें',
      'full_name': 'पूरा नाम',
      'phone_number': 'फ़ोन नंबर',
      'already_have_account': 'पहले से खाता है?',
      'search_products': 'उत्पाद खोजें...',
      'categories': 'श्रेणियाँ',
      'featured_products': 'विशेष उत्पाद',
      'farm_fresh_today': 'आज का ताज़ा उत्पाद',
      'farmer_spotlight': 'किसान स्पॉटलाइट',
      'add_to_cart': 'कार्ट में जोड़ें',
      'cart': 'कार्ट',
      'profile': 'प्रोफ़ाइल',
      'logout': 'लॉगआउट',
      'language_selection': 'भाषा चुनें',
      'voice_search': 'खोजने के लिए बोलें',
      'otp_verification': 'ओटीपी सत्यापन',
      'enter_otp': 'आपके फ़ोन पर भेजे गए 6-अंकीय ओटीपी को दर्ज करें',
      'verify': 'سत्यापित करें',
      'resend_otp': 'ओटीपी पुनः भेजें',
      'checkout': 'चेकआउट',
      'subtotal': 'उप-योग',
      'delivery_charge': 'डिलिवरी शुल्क',
      'gst': 'जीएसटी (5%)',
      'total': 'कुल',
      'pay_now': 'अभी भुगतान करें',
      'payment_success': 'भुगतान सफल रहा!',
      'download_invoice': 'इनवॉइस डाउनलोड करें',
      'home': 'होम',
      'my_orders': 'मेरे ऑर्डर',
    },
    'kn': {
      'app_name': 'ಅಗ್ರಿಲಿಂಕ್',
      'tagline': 'ರೈತರನ್ನು ಗ್ರಾಹಕರಿಗೆ ಸಂಪರ್ಕಿಸುವುದು',
      'welcome_back': 'ಸ್ವಾಗತ',
      'login_continue': 'ಮುಂದುವರೆಯಲು ಲಾಗಿನ್ ಮಾಡಿ',
      'email': 'ಇಮೇಲ್',
      'password': 'ಪಾಸ್ವರ್ಡ್',
      'forgot_password': 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?',
      'login': 'ಲಾಗಿನ್',
      'dont_have_account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
      'register': 'ನೋಂದಣಿ ಮಾಡಿ',
      'register_title': 'ಖಾತೆ ರಚಿಸಿ',
      'register_subtitle': 'ಪ್ರಾರಂಭಿಸಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
      'search_products': 'ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...',
      'categories': 'ವರ್ಗಗಳು',
      'featured_products': 'ವೈಶಿಷ್ಟ್ಯಗೊಳಿಸಿದ ಉತ್ಪನ್ನಗಳು',
      'farm_fresh_today': 'ಇಂದಿನ ತಾಜಾ ಫಾರ್ಮ್',
      'farmer_spotlight': 'ರೈತ ಸ್ಪಾಟ್‌ಲೈಟ್',
      'add_to_cart': 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
      'cart': 'ಕಾರ್ಟ್',
      'profile': 'ಪ್ರೊಫൈಲ್',
      'logout': 'ಲಾಗ್ ಔಟ್',
      'language_selection': 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'voice_search': 'ಹುಡುಕಲು ಮಾತನಾಡಿ',
      'otp_verification': 'ಒಟಿಪಿ ಪರಿಶೀಲನೆ',
      'enter_otp': 'ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಲಾದ 6-ಅಂಕಿಯ ಒಟಿಪಿ ನಮೂದಿಸಿ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'resend_otp': 'ಒಟಿಪಿ ಮರುಕಳುಹಿಸಿ',
      'checkout': 'ಚೆಕ್ಔಟ್',
      'subtotal': 'ಉಪಮೊತ್ತ',
      'delivery_charge': 'ವಿತರಣಾ ಶುಲ್ಕ',
      'gst': 'ಜಿಎಸ್ಟಿ (5%)',
      'total': 'ಒಟ್ಟು',
      'pay_now': 'ಈಗ ಪಾವತಿಸಿ',
      'payment_success': 'ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      'download_invoice': 'ಇನ್‌ವಾಯ್ಸ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
      'home': 'ಹೋಮ್',
      'my_orders': 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    },
    'te': {
      'app_name': 'అగ్రిలింక్',
      'tagline': 'రైతులను వినియోగదారులతో అనుసంధానించడం',
      'welcome_back': 'స్వాగతం',
      'login_continue': 'కొనసాగించడానికి లాగిన్ చేయండి',
      'email': 'ఈమెయిల్',
      'password': 'పాస్‌వర్డ్',
      'forgot_password': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'login': 'లాగిన్',
      'dont_have_account': 'ఖాతా లేదా?',
      'register': 'నమోదు చేసుకోండి',
      'register_title': 'ఖాతా సృష్టించండి',
      'register_subtitle': 'ప్రారంభించడానికి సైన్ అప్ చేయండి',
      'full_name': 'పూర్తి పేరు',
      'phone_number': 'ఫోన్ నంబర్',
      'already_have_account': 'ఇప్పటికే ఖాతా ఉందా?',
      'search_products': 'ఉత్పత్తుల కోసం వెతకండి...',
      'categories': 'వర్గాలు',
      'featured_products': 'ప్రత్యేక ఉత్పత్తులు',
      'farm_fresh_today': 'ఈ రోజు తాజా ఫార్మ్',
      'farmer_spotlight': 'రైతు స్పాట్‌లైట్',
      'add_to_cart': 'కార్ట్‌కు జోడించు',
      'cart': 'కార్ట్',
      'profile': 'ప్రొఫైల్',
      'logout': 'లాగ్ అవుట్',
      'language_selection': 'భాషను ఎంచుకోండి',
      'voice_search': 'వెతకడానికి మాట్లాడండి',
      'otp_verification': 'ఓటీపీ వెరిఫికేషన్',
      'enter_otp': 'మీ ఫోన్‌కు పంపిన 6 అంకెల ఓటీపీని నమోదు చేయండి',
      'verify': 'ధృవీకరించు',
      'resend_otp': 'ఓటీపీని మళ్లీ పంపు',
      'checkout': 'చెక్అవుట్',
      'subtotal': 'ఉపమొత్తం',
      'delivery_charge': 'డెలివరీ ఛార్జ్',
      'gst': 'జీఎస్టీ (5%)',
      'total': 'మొత్తం',
      'pay_now': 'ఇప్పుడే చెల్లించండి',
      'payment_success': 'చెల్లింపు విజయవంతమైంది!',
      'download_invoice': 'ఇన్‌వాయిస్ డౌన్‌లోడ్ చేసుకోండి',
      'home': 'హోమ్',
      'my_orders': 'నా ఆర్డర్లు',
    },
    'ta': {
      'app_name': 'அக்ரிலிங்க்',
      'tagline': 'விவசாயிகளை வாடிக்கையாளர்களுடன் இணைக்கிறது',
      'welcome_back': 'வரவேற்கிறோம்',
      'login_continue': 'தொடர உள்நுழையவும்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'login': 'உள்நுழை',
      'dont_have_account': 'கணக்கு இல்லையா?',
      'register': 'பதிவு செய்',
      'register_title': 'கணக்கை உருவாக்கு',
      'register_subtitle': 'தொடங்குவதற்கு பதிவு செய்யவும்',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'search_products': 'தயாரிப்புகளைத் தேடுங்கள்...',
      'categories': 'வகைகள்',
      'featured_products': 'சிறப்பு தயாரிப்புகள்',
      'farm_fresh_today': 'இன்றைய புதிய பண்ணை',
      'farmer_spotlight': 'விவசாயி ஸ்பாட்லைட்',
      'add_to_cart': 'வண்டியில் சேர்',
      'cart': 'வண்டி',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'language_selection': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'voice_search': 'தேட பேசவும்',
      'otp_verification': 'OTP சரிபார்ப்பு',
      'enter_otp': 'உங்கள் தொலைபேசிக்கு அனுப்பப்பட்ட 6 இலக்க OTP ஐ உள்ளிடவும்',
      'verify': 'சரிபார்',
      'resend_otp': 'OTP ஐ மீண்டும் அனுப்பு',
      'checkout': 'செக்அவுட்',
      'subtotal': 'துணைத்தொகை',
      'delivery_charge': 'டெலிவரி கட்டணம்',
      'gst': 'ஜிஎஸ்டி (5%)',
      'total': 'மொத்தம்',
      'pay_now': 'இப்போது செலுத்துங்கள்',
      'payment_success': 'கட்டணம் வெற்றிகரமாக முடிந்தது!',
      'download_invoice': 'விலைப்பட்டியலை பதிவிறக்கவும்',
      'home': 'முகப்பு',
      'my_orders': 'எனது ஆர்டர்கள்',
    },
    'ml': {
      'app_name': 'അഗ്രിലങ്ക്',
      'tagline': 'കർഷകരെ ഉപഭോക്താക്കളുമായി ബന്ധിപ്പിക്കുന്നു',
      'welcome_back': 'സ്വാഗതം',
      'login_continue': 'തുടരുന്നതിനായി ലോഗിൻ ചെയ്യുക',
      'email': 'ഇമെയിൽ',
      'password': 'പാസ്‌വേഡ്',
      'forgot_password': 'പാസ്‌വേഡ് മറന്നുപോയോ?',
      'login': 'ലോഗിൻ',
      'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ?',
      'register': 'രജിസ്റ്റർ ചെയ്യുക',
      'register_title': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'register_subtitle': 'ആരംഭിക്കാൻ സൈൻ അപ്പ് ചെയ്യുക',
      'full_name': 'മുഴുവൻ പേര്',
      'phone_number': 'ഫോൺ നമ്പർ',
      'already_have_account': 'നേരത്തെ അക്കൗണ്ട് ഉണ്ടോ?',
      'search_products': 'ഉൽപ്പന്നങ്ങൾ തിരയുക...',
      'categories': 'വിഭാഗങ്ങൾ',
      'featured_products': 'പ്രത്യേക ഉൽപ്പന്നങ്ങൾ',
      'farm_fresh_today': 'ഇന്നത്തെ ഫ്രഷ് ഫാം',
      'farmer_spotlight': 'കർഷക സ്പോട്ട്‌ലൈറ്റ്',
      'add_to_cart': 'കാർട്ടിലേക്ക് ചേർക്കുക',
      'cart': 'കാർട്ട്',
      'profile': 'പ്രൊഫൈൽ',
      'logout': 'ലോഗ് ഔട്ട്',
      'language_selection': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
      'voice_search': 'തിരയാൻ സംസാരിക്കുക',
      'otp_verification': 'ഒടിപി വെരിഫിക്കേഷൻ',
      'enter_otp': 'നിങ്ങളുടെ ഫോണിലേക്ക് അയച്ച 6 അക്ക ഒടിപി നൽകുക',
      'verify': 'സ്ഥിരീകരിക്കുക',
      'resend_otp': 'ഒടിപി വീണ്ടും അയയ്ക്കുക',
      'checkout': 'ചെക്ക്ഔട്ട്',
      'subtotal': 'സബ് ടോട്ടൽ',
      'delivery_charge': 'ഡെലിവറി ചาร์ജ്',
      'gst': 'ജിഎസ്ടി (5%)',
      'total': 'ആകെ',
      'pay_now': 'ഇപ്പോൾ പണമടയ്ക്കുക',
      'payment_success': 'പേയ്‌മെന്റ് വിജയകരമായി!',
      'download_invoice': 'ഇൻവോയ്സ് ഡൗൺലോഡ് ചെയ്യുക',
      'home': 'ഹോം',
      'my_orders': 'എന്റെ ഓർഡറുകൾ',
    }
  };
}
