-- ============================================================
-- 17_pricing_analytics.sql
-- Price history tracking and ML price predictions
-- Tables: price_history, ml_price_prediction
-- Depends on: 03_master_tables.sql (crop)
-- ============================================================

-- 1. PRICE_HISTORY
-- Audit trail of crop price changes over time.
-- Feeds the ML model and helps customers understand price trends.
-- Business rules:
--  - new_price must always be positive
--  - source categorizes what triggered the price change
--  - effective_from is when the new price became active
CREATE TABLE IF NOT EXISTS price_history (
    price_history_id    UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    crop_id             UUID        NOT NULL REFERENCES crop(crop_id) ON DELETE CASCADE,
    old_price           DECIMAL(10, 2) CHECK (old_price >= 0),
    new_price           DECIMAL(10, 2) NOT NULL CHECK (new_price >= 0),
    source              VARCHAR(30) CHECK (source IN ('Manual', 'Market', 'Demand', 'Prediction')),
    changed_by          UUID        REFERENCES users(user_id) ON DELETE SET NULL,
    effective_from      TIMESTAMPTZ DEFAULT NOW(),
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ML_PRICE_PREDICTION
-- Forward-looking price predictions generated by the ML engine.
-- Used to show customers expected price trends and help farmers plan.
-- Business rules:
--  - effective_from < effective_to
--  - factors is a free-text field capturing model inputs
--    (e.g., 'Season: Monsoon, Demand: High, Festival: Onam')
--  - predicted_demand_kg is the forecasted demand during this window
CREATE TABLE IF NOT EXISTS ml_price_prediction (
    prediction_id           UUID        PRIMARY KEY DEFAULT uuid_generate_v4(),
    crop_id                 UUID        NOT NULL REFERENCES crop(crop_id) ON DELETE CASCADE,
    predicted_price         DECIMAL(10, 2) NOT NULL CHECK (predicted_price >= 0),
    predicted_demand_kg     DECIMAL(12, 2),
    factors                 TEXT,       -- Comma-separated or JSON factors string
    confidence_score        DECIMAL(5, 4),    -- 0.0000 to 1.0000
    model_version           VARCHAR(20),
    effective_from          TIMESTAMPTZ NOT NULL,
    effective_to            TIMESTAMPTZ NOT NULL,
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT chk_prediction_dates CHECK (effective_to > effective_from)
);

-- ============================================================
-- INDEXES for pricing tables
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_price_history_crop_id ON price_history(crop_id);
CREATE INDEX IF NOT EXISTS idx_price_history_effective_from ON price_history(effective_from DESC);
CREATE INDEX IF NOT EXISTS idx_price_history_source ON price_history(source);
CREATE INDEX IF NOT EXISTS idx_ml_prediction_crop_id ON ml_price_prediction(crop_id);
CREATE INDEX IF NOT EXISTS idx_ml_prediction_effective ON ml_price_prediction(effective_from, effective_to);
CREATE INDEX IF NOT EXISTS idx_ml_prediction_created ON ml_price_prediction(created_at DESC);
